### ISSUE TITLE
Language select failed.

### ISSUE THREAD

**Issue by CrystalRays** [Him188/Money#5]
Version 3.2.1

Here is the log:
17:04:36 [INFO] [Money] 
17:04:36 [NOTICE] [Money] 欢迎使用经济插件, 请选择语言: (输入 3 次错误或 120 秒内不选择自动选择英文)
17:04:36 [NOTICE] [Money] Hello. Please choose a language: (It will choose English automatically when inputting error 3 times or 120s-timeout)
17:04:36 [INFO] [Money] chs: 简体中文
17:04:36 [INFO] [Money] cht: 繁體中文
17:04:36 [INFO] [Money] eng: English
17:04:36 [NOTICE] [Money] 请输入 chs/cht/eng 选择对应语言.
17:04:36 [NOTICE] [Money] Please type chs/cht/eng to choose.
> cht
> [ERROR] Failed to disable litteral next character
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
        at jline.internal.TerminalLineSettings.waitAndCapture(TerminalLineSettings.java:339)
        at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:311)
        at jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:282)
        at jline.internal.TerminalLineSettings.undef(TerminalLineSettings.java:158)
        at jline.UnixTerminal.disableLitteralNextCharacter(UnixTerminal.java:194)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2455)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2354)
        at cn.nukkit.command.CommandReader.run(CommandReader.java:63)

17:04:43 [INFO] [Money] 
17:04:43 [WARNING] [Money] 你输入了错误的数据. 请选择 chs, cht, eng 其中一个输入.
17:04:43 [INFO] [Money] chs: 简体中文
17:04:43 [INFO] [Money] cht: 繁體中文
17:04:43 [INFO] [Money] eng: English
> eng
> [ERROR] Failed to disable litteral next character
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
        at jline.internal.TerminalLineSettings.waitAndCapture(TerminalLineSettings.java:339)
        at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:311)
        at jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:282)
        at jline.internal.TerminalLineSettings.undef(TerminalLineSettings.java:158)
        at jline.UnixTerminal.disableLitteralNextCharacter(UnixTerminal.java:194)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2455)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2354)
        at cn.nukkit.command.CommandReader.run(CommandReader.java:63)

17:04:46 [INFO] [Money] 
17:04:46 [WARNING] [Money] 你输入了错误的数据. 请选择 chs, cht, eng 其中一个输入.
17:04:46 [INFO] [Money] chs: 简体中文
17:04:46 [INFO] [Money] cht: 繁體中文
17:04:46 [INFO] [Money] eng: English
> chs
> [ERROR] Failed to disable litteral next character
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
        at jline.internal.TerminalLineSettings.waitAndCapture(TerminalLineSettings.java:339)
        at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:311)
        at jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:282)
        at jline.internal.TerminalLineSettings.undef(TerminalLineSettings.java:158)
        at jline.UnixTerminal.disableLitteralNextCharacter(UnixTerminal.java:194)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2455)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2354)
        at cn.nukkit.command.CommandReader.run(CommandReader.java:63)

17:04:50 [INFO] [Money] 
17:04:50 [WARNING] [Money] 你输入了错误的数据. 请选择 chs, cht, eng 其中一个输入.
17:04:50 [INFO] [Money] chs: 简体中文
17:04:50 [INFO] [Money] cht: 繁體中文
17:04:50 [INFO] [Money] eng: English
> chs
17:04:54 [NOTICE] [Money] Language selecting timeout. English is selected

**Comment by CrystalRays** [comment]
I now unzip the jar to get the the file I need...

**Comment by Him188** [comment]
fixed, it will automatically select your system language. And you can use /moneyselectlang to cahnge
