### ISSUE TITLE
Report error every time I press enter in the console when lunch Money 3.2.1 the first time.

### ISSUE THREAD

**Issue by CrystalRays** [Him188/Money#6]
Here is the output in the console:
17:36:09 [INFO] Loading nukkit.yml...
17:36:09 [INFO] Loading server properties...
17:36:09 [INFO] 将 中文(简体) (chs) 设定为基本语言
17:36:09 [INFO] 正在启动支持 Minecraft: PE v1.5 版本的服务器
17:36:09 [INFO] Selected Zlib Provider: 2 (cn.nukkit.utils.ZlibThreadLocal)
17:36:09 [INFO] 正在启动服务器在 0.0.0.0:19132
17:36:09 [INFO] 此服务器正在运行 Nukkit 1.0dev 版本 "蘋果(Apple)派(Pie)" (API 1.0.6)
17:36:09 [INFO] Nukkit 根据 LGPL 许可发行
17:36:10 [INFO] Loading recipes...
17:36:10 [INFO] Loaded 954 recipes.
17:36:10 [INFO] Successfully loaded 0 resource packs
17:36:10 [INFO] 读取中... DbLib v0.2.2
17:36:11 [INFO] [DbLib] Connecting to: jdbc:sqlite:nukkit.db (user: nukkit)
17:36:11 [INFO] [DbLib] DbLib 0.2.2 created by fromgate for nukkit.ru
17:36:11 [INFO] 读取中... WildPlugin v1.0
17:36:11 [INFO] 读取中... Wayback v1.0-SNAPSHOT
17:36:11 [INFO] 读取中... LockIt v2.0
17:36:11 [INFO] Epoll is available. EpollEventLoop will be used.
17:36:11 [INFO] 读取中... EssentialsNK v1.1.0
17:36:11 [INFO] 读取中... SignsEditor v1.0.0
17:36:11 [INFO] 读取中... MoeDB v2.0.0
17:36:11 [INFO] 读取中... Unofficial_Nukkit_Patch vnull
17:36:11 [INFO] 读取中... SlashConsole v0.0.1
17:36:11 [INFO] 读取中... BetterSpawnProtection v0.0.1
17:36:11 [INFO] 读取中... MyOP v1.0.0
17:36:11 [INFO] 读取中... RsFunction v1.0.2
17:36:11 [INFO] 读取中... Money v3.2.1
17:36:11 [INFO] 读取中... RsAuto v1.3.8
17:36:11 [INFO] 读取中... ASkyBlock v0.4.6-STABLE
17:36:11 [INFO] [ASkyBlock] 'en-US.yml' not found in /locale folder. Using /locale/en_US.yml
17:36:11 [INFO] [ASkyBlock] Successfully checked config.yml
17:36:11 [INFO] 读取中... Holograms v2.3
17:36:11 [INFO] 开启中... LockIt v2.0
17:36:11 [INFO] 开启中... MoeDB v2.0.0
17:36:11 [INFO] 开启中... RsFunction v1.0.2
17:36:11 [INFO] [RsFunction] You will use :zh
17:36:11 [INFO] 开启中... Holograms v2.3
17:36:11 [INFO] 准备地图中... "world"
17:36:11 [INFO] 准备地图中... "nether"
17:36:11 [INFO] 开启中... DbLib v0.2.2
17:36:11 [INFO] 开启中... WildPlugin v1.0
17:36:11 [INFO] [WildPlugin] [Wild] enable
17:36:11 [INFO] 开启中... Wayback v1.0-SNAPSHOT
17:36:11 [INFO] [Wayback]
17:36:11 [INFO] [Wayback]                                              __
17:36:11 [INFO] [Wayback]   _   __   _              __                / /
17:36:11 [INFO] [Wayback]  / |/ | |/ / __   __  __ / /    __   _____ / /___
17:36:11 [INFO] [Wayback]  | | /| | // _ | / / / // /__ / _ | / ___// /_ _/
17:36:11 [INFO] [Wayback]  |  / |  // __ |/ /_/ // /_ // __ |/ /__ / /\
17:36:11 [INFO] [Wayback]  |_/  |_//_/  |/\__/ / \__ //_/  |/\___// /\ \
17:36:11 [INFO] [Wayback]                   / /                  / /  \/
17:36:11 [INFO] [Wayback]                __/ /                   |/
17:36:11 [INFO] [Wayback]               /__ /     version 1.0-SNAPSHOT
17:36:11 [INFO] [Wayback]
17:36:11 [INFO] 开启中... EssentialsNK v1.1.0
17:36:11 [INFO] [EssentialsNK] EssentialsNK 加载成功！
17:36:11 [INFO] 开启中... SignsEditor v1.0.0
17:36:11 [INFO] 开启中... Unofficial_Nukkit_Patch vnull
17:36:11 [WARNING] [Unofficial_Nukkit_Patch] Unofficial Nukkit Patch enabled!Author:Shanwer
17:36:11 [INFO] 开启中... SlashConsole v0.0.1
17:36:11 [INFO] 开启中... BetterSpawnProtection v0.0.1
17:36:11 [INFO] 开启中... MyOP v1.0.0
17:36:11 [INFO] [MyOP] |NK MyOP Loading.. by Knight|
17:36:11 [INFO] 开启中... Money v3.2.1
17:36:11 [INFO] [Money] 
17:36:11 [NOTICE] [Money] 欢迎使用经济插件, 请选择语言: (输入 3 次错误或 120 秒内不选择自动选择英文)
17:36:11 [NOTICE] [Money] Hello. Please choose a language: (It will choose English automatically when inputting error 3 times or 120s-timeout)
17:36:11 [INFO] [Money] chs: 简体中文
17:36:11 [INFO] [Money] cht: 繁體中文
17:36:11 [INFO] [Money] eng: English
17:36:11 [NOTICE] [Money] 请输入 chs/cht/eng 选择对应语言.
17:36:11 [NOTICE] [Money] Please type chs/cht/eng to choose.
> chs
17:36:14 [NOTICE] [Money] Language selecting timeout. English is selected
17:36:14 [INFO] 开启中... RsAuto v1.3.8
17:36:14 [INFO] [RsAuto] RsAuto is Loaded
17:36:14 [INFO] 开启中... ASkyBlock v0.4.6-STABLE
17:36:14 [INFO] 准备地图中... "SkyBlock"
17:36:14 [INFO] [ASkyBlock] Enabling ASkyBlock - Founders Edition (API 22)
17:36:14 [INFO] [ASkyBlock] Loading offline messages...
17:36:14 [INFO] [ASkyBlock] Loading the Island Framework
17:36:14 [INFO] [ASkyBlock] Starting Schematic Resource Pack.
17:36:14 [INFO] [ASkyBlock] Successfully loaded 4 Schematic
17:36:14 [INFO] [ASkyBlock] BETA Build detected, use with precautions.
17:36:14 [INFO] [ASkyBlock] ASkyBlock has successfully enabled!
17:36:14 [INFO] 启动 GS4 状态监听器
17:36:14 [INFO] 将 Query 端口设定为 19132
17:36:14 [INFO] Query 运行在 0.0.0.0:19132
17:36:14 [INFO] 默认的游戏模式为：生存模式
17:36:14 [INFO] 启动完成 (5.68s)！如需帮助，请输入 "help" 或 "?"
> 
> [ERROR] Failed to disable litteral next character
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
        at jline.internal.TerminalLineSettings.waitAndCapture(TerminalLineSettings.java:339)
        at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:311)
        at jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:282)
        at jline.internal.TerminalLineSettings.undef(TerminalLineSettings.java:158)
        at jline.UnixTerminal.disableLitteralNextCharacter(UnixTerminal.java:194)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2455)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2354)
        at cn.nukkit.command.CommandReader.run(CommandReader.java:63)

17:36:25 [INFO] CrystalRays[/39.172.175.140:27098] 登入游戏，实体 ID 为 1，坐标位于 (world, 130.7344, 73.0, 129.7512)
17:36:26 [INFO] CrystalRays 加入了游戏
> 
> [ERROR] Failed to disable litteral next character
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
        at jline.internal.TerminalLineSettings.waitAndCapture(TerminalLineSettings.java:339)
        at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:311)
        at jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:282)
        at jline.internal.TerminalLineSettings.undef(TerminalLineSettings.java:158)
        at jline.UnixTerminal.disableLitteralNextCharacter(UnixTerminal.java:194)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2455)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2354)
        at cn.nukkit.command.CommandReader.run(CommandReader.java:63)

/
> [ERROR] Failed to disable litteral next character
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
        at jline.internal.TerminalLineSettings.waitAndCapture(TerminalLineSettings.java:339)
        at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:311)
        at jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:282)
        at jline.internal.TerminalLineSettings.undef(TerminalLineSettings.java:158)
        at jline.UnixTerminal.disableLitteralNextCharacter(UnixTerminal.java:194)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2455)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2354)
        at cn.nukkit.command.CommandReader.run(CommandReader.java:63)

17:36:44 [INFO] 未知的指令。请使用 /help 来显示指令列表。
> /
> [ERROR] Failed to disable litteral next character
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
        at jline.internal.TerminalLineSettings.waitAndCapture(TerminalLineSettings.java:339)
        at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:311)
        at jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:282)
        at jline.internal.TerminalLineSettings.undef(TerminalLineSettings.java:158)
        at jline.UnixTerminal.disableLitteralNextCharacter(UnixTerminal.java:194)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2455)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2354)
        at cn.nukkit.command.CommandReader.run(CommandReader.java:63)

17:36:45 [INFO] 未知的指令。请使用 /help 来显示指令列表。
> stop
> [ERROR] Failed to disable litteral next character
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
        at jline.internal.TerminalLineSettings.waitAndCapture(TerminalLineSettings.java:339)
        at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:311)
        at jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:282)
        at jline.internal.TerminalLineSettings.undef(TerminalLineSettings.java:158)
        at jline.UnixTerminal.disableLitteralNextCharacter(UnixTerminal.java:194)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2455)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2354)
        at cn.nukkit.command.CommandReader.run(CommandReader.java:63)

17:36:49 [INFO] [CONSOLE: 正在关闭服务器]
17:36:49 [INFO] 关闭中... Holograms v2.3
17:36:49 [INFO] 关闭中... ASkyBlock v0.4.6-STABLE
17:36:49 [INFO] [ASkyBlock] Saving islands framework
17:36:49 [INFO] [ASkyBlock] Saving worlds...
17:36:49 [INFO] [ASkyBlock] Closing databases...
17:36:49 [INFO] [ASkyBlock] Saving offline messages...
17:36:49 [INFO] [ASkyBlock] ASkyBlock has successfully disabled. Goodbye
17:36:49 [INFO] 关闭中... RsAuto v1.3.8
17:36:49 [INFO] [RsAuto] RsAuto is unloaded
17:36:49 [INFO] 关闭中... Money v3.2.1
17:36:49 [INFO] 关闭中... RsFunction v1.0.2
17:36:49 [INFO] 关闭中... MyOP v1.0.0
17:36:49 [INFO] 关闭中... BetterSpawnProtection v0.0.1
17:36:49 [INFO] 关闭中... SlashConsole v0.0.1
17:36:49 [INFO] 关闭中... Unofficial_Nukkit_Patch vnull
17:36:49 [INFO] 关闭中... MoeDB v2.0.0
17:36:49 [INFO] 关闭中... SignsEditor v1.0.0
17:36:49 [INFO] 关闭中... EssentialsNK v1.1.0
17:36:49 [INFO] 关闭中... LockIt v2.0
17:36:49 [INFO] 关闭中... Wayback v1.0-SNAPSHOT
17:36:49 [INFO] [Wayback]
17:36:49 [INFO] [Wayback]                                              __
17:36:49 [INFO] [Wayback]   _   __   _              __                / /
17:36:49 [INFO] [Wayback]  / |/ | |/ / __   __  __ / /    __   _____ / /___
17:36:49 [INFO] [Wayback]  | | /| | // _ | / / / // /__ / _ | / ___// /_ _/
17:36:49 [INFO] [Wayback]  |  / |  // __ |/ /_/ // /_ // __ |/ /__ / /\
17:36:49 [INFO] [Wayback]  |_/  |_//_/  |/\__/ / \__ //_/  |/\___// /\ \
17:36:49 [INFO] [Wayback]                   / /                  / /  \/
17:36:49 [INFO] [Wayback]                __/ /                   |/
17:36:49 [INFO] [Wayback]               /__ /     version 1.0-SNAPSHOT
17:36:49 [INFO] [Wayback]
17:36:49 [INFO] 关闭中... WildPlugin v1.0
17:36:49 [INFO] [WildPlugin] [Wild] has been disabled!
17:36:49 [INFO] 关闭中... DbLib v0.2.2
17:36:49 [INFO] CrystalRays 离开了游戏
17:36:49 [INFO] CrystalRays[/39.172.175.140:27098] 登出游戏，原因： 服务器已关闭
17:36:49 [INFO] 正在移除地图 "world"
17:36:49 [INFO] 正在移除地图 "nether"
17:36:49 [INFO] 正在移除地图 "SkyBlock"
17:36:49 [INFO] Stopping other threads

**Comment by CrystalRays** [comment]
I means the error: [ERROR] Failed to disable litteral next character
If I disabled the money, this error won't happen

**Comment by Him188** [comment]
fixed
