### ISSUE TITLE
循环依赖？

### ISSUE THREAD

**Issue by starlight196** [Him188/Money#8]
无法读取插件 "Money"：检测到循环依赖

**Comment by Him188** [comment]
依赖MoeDB。
请先检查是否已安装
[moedb](https://github.com/Him188/MoeDB)

**Comment by starlight196** [comment]
已安装

**Comment by Him188** [comment]
检查moedb是否启动成功，不然也不知道是什么问题了...

**Comment by starlight196** [comment]
00:55:17 [INFO ] 读取 BetterVanillaGenerator v1.0.1 中
00:55:17 [INFO ] 读取 LockIt v2.2 中
00:55:17 [INFO ] 读取 RealKeepInventory v1.2.2 中
00:55:17 [INFO ] 读取 MoeDB v1.0.0 中
00:55:17 [INFO ] 读取 MobPlugin v1.10.3 中
00:55:17 [INFO ] 读取 LuckyBlock v1.0.0 中
00:55:17 [INFO ] 读取 Advanced-Welcome v0.1 中
00:55:17 [INFO ] 读取 Money v3.3 中
00:55:17 [FATAL] Could not execute taskHandler 19: redis/clients/jedis/exceptions/JedisConnectionException
00:55:17 [ERROR] Throwing
java.lang.RuntimeException: java.lang.NoClassDefFoundError: redis/clients/jedis/exceptions/JedisConnectionException
	at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:299) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:277) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.tick(Server.java:1132) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:903) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.start(Server.java:880) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.<init>(Server.java:565) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NoClassDefFoundError: redis/clients/jedis/exceptions/JedisConnectionException
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_222]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_222]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_222]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_222]
	at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:56) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:272) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.reload(Server.java:796) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:28) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.dispatchCommand(Server.java:751) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.console.NukkitConsole.lambda$runCommand$0(NukkitConsole.java:35) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296) ~[nukkit-1.0-SNAPSHOT.jar:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: redis.clients.jedis.exceptions.JedisConnectionException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_222]
	at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_222]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_222]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_222]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_222]
	at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:56) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:272) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.reload(Server.java:796) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:28) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.dispatchCommand(Server.java:751) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.console.NukkitConsole.lambda$runCommand$0(NukkitConsole.java:35) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296) ~[nukkit-1.0-SNAPSHOT.jar:?]
	... 6 more

**Comment by starlight196** [comment]
不用money就没有报错

**Comment by Him188** [comment]
它在连接Redis服务器, 你看看你是不是用的moedb-shaded

**Comment by starlight196** [comment]
我可能少装了什么，用这个插件要在服务器上装哪些东西？

**Comment by Him188** [comment]
不需要额外安装。你要下载MoeDB-x.x.x-shaded.jar
如果你已经下载安装了，请考虑删除plugins/money（这将会丢失数据）

**Comment by starlight196** [comment]
GitHub上只有1.0.0Pre和1.0.0Pre-fix...

**Comment by Him188** [comment]
那个过期了，麻烦去这里 http://mamoe.net:2333/

**Comment by Him188** [comment]
服务器死了，得等一等....

**Comment by starlight196** [comment]
昨天就打不开。。。

**Comment by starlight196** [comment]
现在还是打不开。。。

**Comment by starlight196** [comment]
大佬是弃坑了吗

**Comment by Him188** [comment]
还没，现在学习很忙

**Comment by Him188** [comment]
服务器是朋友的，他那边在维护，我也没时间去移repo

**Comment by Him188** [comment]
@olddrive  先用这个吧, 服务器不知道什么时候维护好
[MoeDB&Money.zip](https://github.com/Him188/Money/files/3562226/MoeDB.Money.zip)
